server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 604800
spring:
  application:
    name: yudi-cloud-backend
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  session:
    store-type: redis
    timeout: 604800
mybatis-plus:
  configuration:
    #字段驼峰映射
    map-underscore-to-camel-case: false
    #日志仅开发
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDelete #全局逻辑删除的实体字段名
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    # aaa"
    version: 1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.yudi.cloud.controller

# Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒，-1 代表永不过期）
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从 cookie 中读取 token
  is-read-cookie: false
  # 是否从 header 中读取 token
  is-read-head: true
  # 是否从 请求体 中读取 token
  is-read-body: false
  # 是否在登录后将 Token 写入到响应头
  is-write-head: true
  # 是否在登录后将 Token 写入到响应体
  is-write-body: false
  # 是否在登录后将 Token 写入到 Cookie
  is-write-cookie: false
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    # Redis数据库索引
    database: 1
    # Redis服务器地址
    host: 123.56.130.245
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Yunstudy99.
    # 连接超时时间
    timeout: 5000